name: azure login
run-name: azure login
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'scenario tags'
        required: true
        type: string
jobs:
  azure-login:
    runs-on: ubuntu-latest
    steps:
      - name: azure login using action
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      - name: az account show
        uses: azure@cli@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az account show -o yaml
  

